### ISSUE TITLE
Miscellaneous Long Term Goals

### ISSUE THREAD

**Issue by AlphaAtlas** [AlphaAtlas/VapourSynth-Super-Resolution-Helper#2]
- [ ] Investigate deeper cross platform/AMD support. ~~It seems that AMD's deep learning framework development is mostly geared towards Linux? See: https://rocm.github.io/install.html~~ The ROCm MXNet branch isn't really going anywhere, but maybe some models can run on OpenCV?

- [ ] Investigate more GPU heavy VS filters, since this project installs CUDA/cuDNN anyway. See [this](http://vsdb.top/) and [this](https://github.com/WolframRhodium/muvsfunc/tree/master/Collections) 

- [ ] Pre-Train networks from other sources

- [ ] Upload some visual comparisons between the existing upscaling filters on the wiki.

**Comment by theChaosCoder** [comment]
For the dependecies I found this very usefull project https://github.com/brechtsanders/pedeps
It can show the dll / file dependecies and has also this tool: copypedeps, which can copy "all" dependencies to one place (hint: it does not copy files from C:\Windows\*)

**Comment by AlphaAtlas** [comment]
Thanks. In case you can't tell, I'm a bit of a novice (especially when it comes to C/C++), but that could help me make other GPU VS plugins cooperate down the road. 

The big sticking point for this particular installer is kice's MXNet plugin, which needs matching flavors of mxnet, CUDA, and cuDNN. The latter is gated behind a registration page and a restrictive license, meaning it can't just be redistributed with a release or package, so the install script downloads a (somehow legal and public?) Anaconda cuDNN mirror and unzips it to the right spot. Meanwhile, AFAIK, CUDA has to be installed to function on Windows. I don't believe all the associated .dlls are dependencies that can be gathered into one spot for a VS plugin. 

The MXNet ROCm branch isn't stable yet, so I probably won't look into that anytime soon.

**Comment by AlphaAtlas** [comment]
Ah, I'm stupid, as I just saw the command line utilities.

Thanks!
