### ISSUE TITLE
ERROR: unknown command "installvsgan--upgrade"

### ISSUE THREAD

**Issue by coderynx** [AlphaAtlas/VapourSynth-Super-Resolution-Helper#8]
![Error](https://user-images.githubusercontent.com/23385887/67200699-d4474d80-f404-11e9-81b5-855162832f7a.PNG)

**Comment by AlphaAtlas** [comment]
Fixed. Thanks for testing the Nvidia stuff!

You can either run the installer again, or (most simply) just click the "Open Console for Pip.bat", and type "python.exe -m pip install vsgan" to get the filter.

**Comment by AlphaAtlas** [comment]
I think I've fixed this twice now, let me know if it pops up again.
